crates/stark-backend/src/air_builders/symbolic/dag.rs, crates/stark-backend/src/air_builders/symbolic/mod.rs, crates/stark-backend/src/air_builders/symbolic/symbolic_expression.rs, crates/stark-backend/src/air_builders/symbolic/symbolic_variable.rs, crates/stark-backend/src/air_builders/verifier.rs, crates/stark-backend/src/interaction/debug.rs, crates/stark-backend/src/interaction/stark_log_up.rs
To avoid exponential blowup in the evaluation of the symbolic syntax tree, we convert it into a DAG with topological sort and evaluate topologically (currently single threaded) to avoid there is not duplicate evaluations. The main note is that `Arc` should be hashed using `ptr::hash`.
This PR will not switch the serialization of vkey to DAG. This will be done in a followup where we switch the main interfaces to use the DAG, and `SymbolicExpression` should only be an internally used struct.
towards INT-2905
=> [feat] SymbolicConstraints as DAG

Cargo.toml, crates/stark-backend/src/air_builders/symbolic/dag.rs, crates/stark-backend/src/air_builders/symbolic/mod.rs, crates/stark-backend/src/air_builders/verifier.rs, crates/stark-backend/src/interaction/mod.rs
Including interactions. Doing this for now to keep interfaces the same.
In the upcoming frontend-backend split, we will make a breaking
interface change to switch to using the DAG as the primary interface and
make `SymbolicExpression` and `SymbolicConstraints` private (or remove
entirely).
Closes INT-2905
I checked locally that the `openvm` book example with keccak now has instant keygen time and the vkey is `338K`.
=> feat: serialize `SymbolicConstraints` as DAG 

crates/stark-backend/src/air_builders/debug/check_constraints.rs, crates/stark-backend/src/air_builders/debug/mod.rs, crates/stark-backend/src/engine.rs, crates/stark-backend/src/prover/mod.rs, crates/stark-backend/src/utils.rs, crates/stark-backend/tests/cached_lookup/mod.rs, crates/stark-backend/tests/interaction/mod.rs, crates/stark-backend/tests/partitioned_sum_air/mod.rs
So `prove` no longer requires `AnyRap`.
I did not remove `AnyRap` from `AirProofInput` because many testing functions use it. I plan to split `AirProofInput` into `SingleKeygenCtx` and `SingleProvingCtx` for the with `AnyRap` and without `AnyRap` variants.
**Note:** this pr is into a `feat/bal` branch, not `main`.
=> chore: move debug out of prover

crates/stark-sdk/src/bench/mod.rs
Currently, calling the `run_with_metric_collection` multiple times in the same thread, or even across different threads fails. This is because it sets global state by calling `tracing::subscriber::set_global_default` and `metrics::set_global_recorder`. These functions error when called more than once.
The fix is to replace them with `tracing::subscriber::set_default` and `metrics::with_local_recorder` which use local and temporary state instead.
This change allows `run_with_metric_collection` to be used in tests, since we want to be able to run multiple tests.
=> [fix] calling run_with_metric_collection multiple times fails

crates/stark-backend/src/engine.rs, crates/stark-backend/src/interaction/mod.rs, crates/stark-backend/src/prover/coordinator.rs, crates/stark-backend/src/prover/cpu/mod.rs, crates/stark-backend/src/prover/cpu/quotient/mod.rs, crates/stark-backend/src/prover/hal.rs, crates/stark-backend/src/prover/metrics.rs, crates/stark-backend/src/prover/mod.rs, crates/stark-backend/src/prover/types.rs, crates/stark-sdk/src/dummy_airs/interaction/dummy_interaction_air.rs, crates/stark-sdk/src/dummy_airs/interaction/mod.rs
Even if they are buffers, make them owned types (no Clone) so that when they are dropped, the device memory is automatically deallocated.
CpuDevice types still use `Arc` because lifetimes and ownership is extremely annoying.
There is also a distinction that main trace is owned, but preprocessed / cached trace is borrowed. The rationale is that any cached data could live on the device and outlive the lifetime of a single proof. Any deallocation should be manually done.
Closes INT-3042
=> chore: make device memory types owned

Cargo.toml, crates/stark-backend/src/prover/coordinator.rs, crates/stark-backend/src/prover/cpu/mod.rs, crates/stark-backend/src/prover/cpu/quotient/mod.rs, crates/stark-backend/src/prover/cpu/quotient/single.rs, crates/stark-backend/src/prover/hal.rs, docs/metrics.md
Just have one function for quotient poly eval and commit.
Importantly we update the CPU implementation to avoid additional memory allocation
when creating a **view** of the trace LDE matrices necessary for quotient poly
evaluation.
I explain the issue here: https://github.com/Plonky3/Plonky3/issues/626
=> feat: simplify QuotientCommitter trait for performance

crates/stark-backend/src/engine.rs, crates/stark-sdk/src/engine.rs
only one testing function, removes unused `run_simple_test_impl`
closes INT-3115
=> chore: cleanup `StarkEngine`

crates/stark-sdk/Cargo.toml, crates/stark-sdk/examples/profile.sh, crates/stark-sdk/examples/prove_keccak_baby_bear_poseidon2.rs
Example with end to end keygen, proving, verify for keccak-air from plonky3 (no interactions). 
Added a script that builds and profiles the proving using [samply](https://github.com/mstange/samply)
Closes INT-3185
=> example: profiling prove keccak-air using SDK

crates/stark-backend/src/air_builders/symbolic/dag.rs, crates/stark-backend/src/verifier/folder.rs
This pr aims to have `dag.constraint_idx` to be sorted.
For complex circuit like keccak, the number of nodes in the dag is very large (around 50k). However, the locality pattern still applies in this case which means each node in the dag only depends on nodes with indices that are close to its index. 
This means we can use a **small** vector for caching the intermediates (we call node like `main / preprocessed / permutation` leaf node, while we call node like `add / mul / sub / neg` as intermediate node). In the special keccak case, we can reduce it from 50k to 200.
If the `constraint_idx` is sorted, then we can free the node's memory (can be reused) after we finished accumulating them into `accumulator`.
=> Feat: require `dag.constraint_idx` is sorted

crates/stark-backend/src/chip.rs, crates/stark-backend/src/lib.rs
We have found the trait not useful or flexible enough for custom state loading/storing purposes. Implementations need to be much more aware of the buffer where state needs to be deserialized from or serialized to. We remove the trait and allow users to create their own custom trait for specific use cases.
=> chore: remove `Stateful` trait

crates/stark-backend/src/prover/coordinator.rs, crates/stark-backend/src/verifier/mod.rs
Fiat-Shamir says that everything in the proof should be observed. Since AIR IDs can be variable, they should also be observed.
=> feat: observe AIR IDs in Fiat-Shamir transcript

crates/stark-backend/src/verifier/error.rs, crates/stark-backend/src/verifier/mod.rs
A good guiding principle was that `challenge.observe_slice` does not observe the length of a slice, so for every use of observe slice where we don't observe length separately, it should mean that the verifier must validate that the length matches an expected length in the vkey.
=> fix: verifier should check proof shape

Cargo.toml
Update plonky3 commit to include the patch https://github.com/Plonky3/Plonky3/pull/759 fixing the Rust FRI verifier. 
Description of the security issue: https://github.com/Plonky3/Plonky3/security/advisories/GHSA-m23j-cj9m-ppg9
=> fix(plonky3): update plonky3 commit

Cargo.toml, crates/stark-sdk/Cargo.toml, crates/stark-sdk/src/lib.rs
Adds Plonky3's `KoalaBear` as an export in `stark-sdk`.
=> chore: add KoalaBear export to stark-sdk

crates/stark-backend/src/prover/cpu/mod.rs, crates/stark-backend/src/prover/cpu/quotient/mod.rs
PR targeting https://github.com/openvm-org/stark-backend/pull/68
I noticed that permutation trace commitment is doing TWO needless clones: first `RowMajorMatrix::flatten_to_base` creates a whole new vector by collecting individual flatten to base when the extension field matrix can just be transmuted. Secondly, the permutation trace is never used after it is committed, so we should not use `TraceCommitter` (which clones) but instead use `pcs.commit` directly.
I have add a `transmute_to_base` function to replace `flatten_to_base`. There doesn't seem a good way to have the compiler check the required safety assumptions, so I just document it. (The `BinomialExtensionField` implementation of `ExtensionField` satisfies the assumptions.)
The quotient polynomial matrices also saves clones by …
=> perf: avoid needless clones in permutation trace commit

crates/stark-backend/src/engine.rs, crates/stark-backend/src/interaction/fri_log_up.rs, crates/stark-backend/src/interaction/mod.rs, crates/stark-backend/src/prover/coordinator.rs, crates/stark-backend/src/prover/cpu/mod.rs, crates/stark-backend/src/prover/cpu/quotient/mod.rs, crates/stark-backend/src/prover/hal.rs, crates/stark-backend/src/prover/types.rs, crates/stark-sdk/src/dummy_airs/interaction/mod.rs
Changed the traits slightly so that traces are passed without borrowing. The main reason is the realization that preprocessed and main traces are only used to generate the permutation trace, so they can be dropped immediately after this step (in `partially_prove`). Afterwards, only LDEs need to be used.
There is some improvement in how the handling of preprocessed / cached trace is done: sometimes you may want to not drop these (so they really stay in memory) and sometimes you may want to drop it to lower peak memory. Maybe some `Shared**` type may make this clearer, but for now I just opted to use owned versions of everything because in practice we are using smart pointers (`Arc`) around everything, so one can get around sharing with some cloning if necessary.
Note that right now the …
=> feat!: drop main trace earlier for lower peak memory

crates/stark-backend/src/interaction/fri_log_up.rs, crates/stark-backend/src/prover/cpu/mod.rs, crates/stark-backend/src/prover/cpu/quotient/mod.rs, crates/stark-backend/src/prover/cpu/quotient/single.rs, crates/stark-backend/src/prover/metrics.rs, crates/stark-sdk/src/config/baby_bear_bytehash.rs, crates/stark-sdk/src/config/baby_bear_poseidon2.rs, crates/stark-sdk/src/config/baby_bear_poseidon2_root.rs, crates/stark-sdk/src/config/goldilocks_poseidon.rs
Follow up of https://github.com/openvm-org/stark-backend/pull/68 where the main idea was that for perm and quotient PCS commitments, we generate the matrices and then immediate apply cosetLDE which does in-place DFT which resizes the matrix to `trace_height * log_blowup`. To avoid re-allocation, we allocate the right amount of space from the start.
While doing this, I noticed that we were using plonky3's `Domain::split_evals` to split the quotient poly into chunks: this does a full copy of the quotient matrix (basically a transpose) -- this is totally unnecessary since we generate the whole quotient poly using a `par_iter`! Under (what I think is) a minor assumption that we always split quotient polys in this way, I got rid of it so now there's no copy. …
=> feat: reserve capacity for perm & quotient LDE; avoid copy for quotient split

.github/workflows/tests-cuda.yml, crates/cuda-backend/src/opener/mod.rs
We don't use the type itself, but we need to use the correct type to avoid compile errors.
The `ValMmcs` has packed types which is phantom data and only used by the prover (which we ignore since we use the cuda prover), and the proof types only used the associated `::Value` which is SIMD-independent.
closes INT-4848
=> fix: use plonky3 `Packed` types for SIMD compatibility

Cargo.toml, crates/cuda-common/src/common.rs, crates/cuda-common/src/memory_manager.rs
Reverts openvm-org/stark-backend#111
Performance regression in pcs opening: https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/17335892603
=> Revert "chore(cuda): Sync when release big buffer & bump version to `1.2.0-rc.8`"

crates/cuda-backend/cuda/src/fri.cu, crates/cuda-backend/src/cuda/kernels.rs, crates/cuda-backend/src/opener/mod.rs, crates/cuda-backend/src/opener/ops.rs
Closes INT-4618
Making all `reduced_openings` polynomial & `z_diff_invs` in natural order.
- We still use z_diff_inv for max height only => double bit reverse required for smaller matrices
- Also I've changed some buffers with one value to just values
=> perf(cuda): Opener in natural order
